<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Rsk.Enforcer.AuthZen" Version="6.1.1"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Policies\global.alfa" />
      <EmbeddedResource Include="Policies\global.alfa" />
      <None Remove="Policies\expenses.alfa" />
      <EmbeddedResource Include="Policies\expenses.alfa" />
    </ItemGroup>
</Project>
